include: .gitlab/jobs.gitlab-ci.yml

build container image:
  extends: .kaniko build container image job
  variables:
    KANIKO_DESTINATIONS: addword/dive-into-5g-bits-generator
    KANIKO_DOCKERFILE: qpsk-bits-generator/Dockerfile
