version: '3'
services:
  terminal:
    build:
      context: .
      dockerfile: terminal.Dockerfile
    volumes:
    - .:/var/workspace
    working_dir: /var/workspace
  modulator:
    build:
      context: .
      dockerfile: qpsk-modulator/Dockerfile
  demodulator:
    build:
      context: .
      dockerfile: qpsk-demodulator/Dockerfile
  bits-generator:
    build:
      context: .
      dockerfile: qpsk-bits-generator/Dockerfile
  ber-calculator:
    build:
      context: .
      dockerfile: qpsk-ber-calculator/Dockerfile
  random-bits:
    image: alpine
    entrypoint:
    - sh
    - -c
    - |-
      if [ "$$0" != "sh" ]; then
        tr -cd '01' </dev/urandom | fold $${0:+-w$$0} | head -n1
      else
        tr -cd '01' </dev/urandom
      fi
  noise-injector:
    build:
      context: .
      dockerfile: qpsk-noise-injector/Dockerfile
  workplace:
    build:
      context: .
      dockerfile: workplace.Dockerfile
    volumes:
    - .:/var/workspace
