version: '3'
services:
  terminal:
    build:
      context: .
      dockerfile: terminal.Dockerfile
    volumes:
    - .:/var/workspace
    working_dir: /var/workspace
  modulator:
    build:
      context: .
      dockerfile: qpsk-modulator/Dockerfile
    stdin_open: true
  demodulator:
    build:
      context: .
      dockerfile: qpsk-demodulator/Dockerfile
    stdin_open: true