.kaniko build container image job:
  stage: build
  resource_group: ${KANIKO_DESTINATIONS}
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    KANIKO_CONTEXT: .
    KANIKO_DOCKERFILE: Dockerfile
    KANIKO_EXECUTOR: /kaniko/executor
  script:
  - if [ "$CONTAINER_IMAGE_REGISTRY_USER" -a "$CONTAINER_IMAGE_REGISTRY_PASSWORD" ]; then
  -
    - >-
      CONTAINER_IMAGE_REGISTRY_CREDS=$(
      echo -n ${CONTAINER_IMAGE_REGISTRY_USER}:${CONTAINER_IMAGE_REGISTRY_PASSWORD} | base64
      )
    - >-
      echo
      "{\"auths\":{\"${CONTAINER_IMAGE_REGISTRY_HOST}\":{\"auth\":\"${CONTAINER_IMAGE_REGISTRY_CREDS}\"}}}"
      > /kaniko/.docker/config.json
  - fi
  - >-
    KANIKO_EXECUTOR_DESTINATION_OPTIONS=$(for DESTINATION in $KANIKO_DESTINATIONS;
    do echo "--destination=${DESTINATION}"; done)
  - >-
    $KANIKO_EXECUTOR
    ${KANIKO_CONTEXT:+--context="$KANIKO_CONTEXT"}
    ${KANIKO_DOCKERFILE:+--dockerfile="$KANIKO_DOCKERFILE"}
    ${KANIKO_EXECUTOR_DESTINATION_OPTIONS:---no-push}
