include: .gitlab/jobs.gitlab-ci.yml

build container image:
  extends: .kaniko build container image job
  variables:
    KANIKO_DESTINATIONS: addword/dive-into-5g-ber-calculator
    KANIKO_DOCKERFILE: qpsk-ber-calculator/Dockerfile
