name: build qpsk modulator
on: push
jobs:
  build-container-image:
    name: build container image
    runs-on: ubuntu-latest
    # container:
    #   image: gcr.io/kaniko-project/executor:debug
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: update submodules
      run: |-
        git submodule init
        git submodule update
    - name: list
      run: ls -R
    # - name: kaniko
    #   run: >-
    #     /kaniko/executor
    #     --no-push
    #     --dockerfile=qpsk-modulator/Dockerfile
  list:
    needs:
    - build-container-image
    runs-on: ubuntu-latest
    steps:
    - name: list
      run: ls -R
