name: build qpsk modulator
on: push
jobs:
  build container image:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/kaniko-project/executor:debug
    steps:
    - name: kaniko
      run: >-
        /kaniko/executor --no-push
        --dockerfile=qpsk-modulator/Dockerfile
